# Generated by Django 5.0.7 on 2024-07-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_derivation_salt', models.CharField(default='52bd2c74205960aa028b32865b6ed313', max_length=64)),
            ],
        ),
    ]
