# Generated by Django 5.0.7 on 2024-07-11 02:14

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_clientkeyderivationsalt_salt_vaultentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultentry',
            name='iv',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientkeyderivationsalt',
            name='salt',
            field=models.CharField(default=vault.models.generate_salt, max_length=64),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='password',
            field=models.CharField(),
        ),
    ]
