# Generated by Django 5.0.7 on 2024-08-12 18:01

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_clientkeyderivationsalt_user_totpdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='secret',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
