# Generated by Django 5.0.7 on 2024-09-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_alter_totpdevice_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('name', models.CharField(max_length=255)),
                ('VaultEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.vaultentry')),
            ],
        ),
    ]
