# Generated by Django 5.0.7 on 2024-09-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_fileentry_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
