# Generated by Django 5.0.7 on 2024-09-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_alter_fileentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.CharField(),
        ),
    ]
