# Generated by Django 5.0.7 on 2024-09-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_alter_fileentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
